let items =[
    {
        item_id : "1",
        item_image: '../items/1.webp',
        item_rating: {
            stars : "4.2",
            likes : "47.3k",
        },
        item_companyname : "Roadster",
        item_name : "Pure Cotton T-shirt",
        item_sellingprice : "244",
        item_actualprice : "499",
        item_discount : "51",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "2",
        item_image: '../items/2.webp',
        item_rating: {
            stars : "4",
            likes : "64",
        },
        item_companyname : "Campus Sutra",
        item_name : "Men Slim Fit Cotton Jeans",
        item_sellingprice : "900",
        item_actualprice : "1699",
        item_discount : "47",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "3",
        item_image: '../items/3.webp',
        item_rating: {
            stars : "4.2",
            likes : "179",
        },
        item_companyname : "Jompers",
        item_name : "Sequinned Pure Cotton Kurta",
        item_sellingprice : "1289",
        item_actualprice : "4299",
        item_discount : "70",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "4",
        item_image: '../items/4.webp',
        item_rating: {
            stars : "3.8",
            likes : "4.2k",
        },
        item_companyname : "Saree mall",
        item_name : "Floral Saree",
        item_sellingprice : "791",
        item_actualprice : "3599",
        item_discount : "78",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "5",
        item_image: '../items/5.webp',
        item_rating: {
            stars : "4.1",
            likes : "630",
        },
        item_companyname : "Denill",
        item_name : "Women Open Toe Flats",
        item_sellingprice : "489",
        item_actualprice : "1399",
        item_discount : "65",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "6",
        item_image: '../items/6.webp',
        item_rating: {
            stars : "4.3",
            likes : "1.3k",
        },
        item_companyname : "Tommy Hilfiger",
        item_name : "Men Analogue Watch",
        item_sellingprice : "5480",
        item_actualprice : "10960",
        item_discount : "50",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "7",
        item_image: '../items/7.webp',
        item_rating: {
            stars : "3.8",
            likes : "48",
        },
        item_companyname : "AMICO",
        item_name : "Men Mesh Running Shoes",
        item_sellingprice : "624",
        item_actualprice : "2499",
        item_discount : "75",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "8",
        item_image: '../items/8.webp',
        item_rating: {
            stars : "4.4",
            likes : "1.6k",
        },
        item_companyname : "LOreal",
        item_name : "Hydra Filling Night Hair Cream",
        item_sellingprice : "374",
        item_actualprice : "499",
        item_discount : "25",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "9",
        item_image: '../items/9.webp',
        item_rating: {
            stars : "0",
            likes : "0",
        },
        item_companyname : "DREAM CARE",
        item_name : "Waterproof Mattress Protector",
        item_sellingprice : "626",
        item_actualprice : "1899",
        item_discount : "67",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "10",
        item_image: '../items/10.webp',
        item_rating: {
            stars : "3.7",
            likes : "15",
        },
        item_companyname : "Pantaloons Junior",
        item_name : "Girls Slip-On Sneakers",
        item_sellingprice : "719",
        item_actualprice : "799",
        item_discount : "10",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "11",
        item_image: '../items/11.webp',
        item_rating: {
            stars : "0",
            likes : "0",
        },
        item_companyname : "AEROHAVEN",
        item_name : "6-Pieces Pure Cotton Diwan Set",
        item_sellingprice : "749",
        item_actualprice : "2499",
        item_discount : "70",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "12",
        item_image: '../items/12.webp',
        item_rating: {
            stars : "4.6",
            likes : "5",
        },
        item_companyname : "FERANOID",
        item_name : "Print Cotton Peplum Top",
        item_sellingprice : "499",
        item_actualprice : "2499",
        item_discount : "80",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id : "13",
        item_image: '../items/13.webp',
        item_rating: {
            stars : "4.3",
            likes : "75",
        },
        item_companyname : "SASSAFRAS",
        item_name : "Women High Rise Jeans",
        item_sellingprice : "967",
        item_actualprice : "2199",
        item_discount : "56",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    },
    {
        item_id: '14',
        item_image: '../items/14.webp',
        item_rating: {
            stars : "4.3",
            likes : "350",
        },
        item_companyname : "H&M",
        item_name : "Women High Rise Jeans",
        item_sellingprice : "1999",
        item_actualprice : "0",
        item_discount : "0",
        item_returnDate :"14",
        item_deliveryDate : "30 Nov",
    }


]